name: spidr_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.2+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^2.0.3
  flutter_web_browser: ^0.17.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  google_fonts: ^3.0.1

  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  shared_preferences: ^2.0.13
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.11
  intl: ^0.17.0
  dynamic_text_highlighting: ^2.2.0
  camera: ^0.9.4+19
  image_picker: ^0.8.5
  path: ^1.8.0
  path_provider: ^2.0.9

  firebase_messaging: ^11.2.12
  google_sign_in: ^5.2.4
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.1
  flutter_launcher_icons: ^0.9.2
  file_picker: ^4.5.1
  filesize: ^2.0.1
  flutter_downloader: ^1.7.3
  fluttericon: ^2.0.0
  flutter_markdown: ^0.6.9+1
  flutter_image_compress: ^1.1.0
  firebase_analytics: ^9.1.4
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.0
  mime: ^1.0.1
  flutter_icons: ^1.1.0
  carousel_slider: ^4.0.0
  photo_manager: ^2.0.7
  agora_rtc_engine: ^5.2.0
  showcaseview: ^1.1.5
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.3.2
  flash: ^2.0.3+2
  pull_to_refresh: ^2.0.0
  the_apple_sign_in: ^1.1.1
  provider: ^6.0.2
  flutter_linkify: ^5.0.2
  linkify: ^4.1.0
  introduction_screen: ^3.0.2

  video_thumbnail: ^0.5.0
  advance_pdf_viewer: ^2.0.1
  simple_url_preview: ^3.0.1
  tutorial_coach_mark: ^1.2.1
  any_link_preview: ^2.0.6
  giphy_get: ^3.1.0
  algolia: ^1.0.5+1

  video_player: ^2.3.0
  video_compress: ^3.1.0

  flare_flutter: ^3.0.2
  rive: ^0.9.0
  esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2

  permission_handler: ^10.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/icon/SpidrIcon.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/audios/
    - assets/images/
    - assets/icon/
    - assets/icon/bottomNavBar/
    - assets/images/groupPic/
    - assets/images/userPic/
    - assets/imagesp/images/
      #   - images/a_dot_ham.jpeg

      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.

      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages

      # To add custom fonts to your application, add a fonts section here,
      # in this "flutter" section. Each entry in this list should have a
      # "family" key with the font family name, and a "fonts" key with a
      # list giving the asset and other descriptors for the font. For
      # example:
      # fonts:
      #   - family: Schyler
      #     fonts:
      #    - family: WorkSansSemiBold
      #      fonts:
      #        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
      #
      #    - family: WorkSansBold
      #      fonts:
      #        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
      #
    #    - family: WorkSansMedium
    #      fonts:
    #        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
